### ISSUE TITLE
sometimes, bicycle_parking are not displayed.

### ISSUE THREAD

**Issue by XandrexOSM** [Hades1503/OsmAnd_Cycling_Map#5]
description of the issue : 
- sometimes, bicycle_parking are not displayed.

behaviours:
- current behaviour : the blue dot is not displayed
- expected behaviour: the blue dot is displayed.

details & examples :
- for most cases, it works.
- For this following case, it is not displayed. check coordinates : [48.7827, 2.45266](https://www.openstreetmap.org/#map=19/48.7827/2.45266)

screenshots : 

Here is the display with CyclOSM tiles (good): 
![cyclosm photo_2022-07-20_19-58-15](https://user-images.githubusercontent.com/92858966/180050888-a09275fc-d3f2-41e0-9aa0-d46483ec6068.jpg)

Here is the display with CycloRoute (bug):
![cycloroute photo_2022-07-20_19-58-29](https://user-images.githubusercontent.com/92858966/180051000-4b452896-ce23-4136-ba54-cdd090b91db0.jpg)

**Comment by bobeeeze** [comment]
This issue was not a rendering problem, it was a map update problem
