### ISSUE TITLE
CycleRoutes aren't displayed when they are not part of a network

### ISSUE THREAD

**Issue by basings** [Hades1503/OsmAnd_Cycling_Map#9]
Current implementation only displays a cycleroute if its tagged as lcn, rcn, ncn or icn.

**Comment by Louis-LJ** [comment]
> Current implementation only displays a cycleroute if its tagged as lcn, rcn, ncn or icn.

Hello!
we got together to create a common github repo for alternative osmand styles

You can find us at this address:
https://github.com/OsmAnd-Rendering/?view_as=public
